import {
  withOpportunityDefaults,
  type Opportunity,
} from "@/lib/opportunities/types";

/** Demo set — includes eTenders ICT RFQ + PANEL so panel handling is visible. */
export function seedOpportunities(now = new Date()): Opportunity[] {
  const iso = now.toISOString();
  const at = (daysFromNow: number, hour = 11) => {
    const d = new Date(now);
    d.setDate(d.getDate() + daysFromNow);
    d.setHours(hour, 0, 0, 0);
    return d.toISOString();
  };

  const base = (partial: Parameters<typeof withOpportunityDefaults>[0]) =>
    withOpportunityDefaults(partial);

  return [
    base({
      id: "seed-etenders-ict-rfq",
      refNo: "ocds-9t57fa-demo-ict-rfq",
      externalId: "ocds-9t57fa-demo-ict-rfq",
      title: "Custom software development and systems integration RFQ",
      description:
        "Request for quotation for custom software development, API integration, cloud hosting and managed ICT support services for a national department.",
      buyer: "Department of Home Affairs",
      sector: "public",
      source: "eTenders",
      lane: "ICT / IS",
      stage: "Spotted",
      closingAt: at(5, 11),
      briefingAt: at(2, 10),
      briefingCompulsory: false,
      briefingVenue: "Virtual",
      estimatedValueZar: 1850000,
      sourceUrl: "https://www.etenders.gov.za",
      ownerName: "Intake",
      opportunityType: "rfq",
      isPanel: false,
      relevanceScore: 72,
      lowRelevance: false,
      province: "Gauteng",
      category: "Computer programming, consultancy and related activities",
      ocdsMainCategory: "services",
      matchVia: "category",
      contentHash: "seed-ict-rfq-v2",
      documentLinks: [
        {
          title: "RFQ pack",
          url: "https://www.etenders.gov.za",
          format: "application/pdf",
        },
      ],
      contactName: "Procurement Office",
      contactEmail: "procurement@example.gov.za",
      contactPhone: "+27 12 000 0000",
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
    base({
      id: "seed-etenders-ict-panel",
      refNo: "ocds-9t57fa-demo-ict-panel",
      externalId: "ocds-9t57fa-demo-ict-panel",
      title: "Panel of software developers and ICT service providers",
      description:
        "Framework agreement to establish a panel of prequalified software developers for digitisation, web applications, and ICT managed services over a 36-month term. Appointment enables invited work without re-competing.",
      buyer: "State Information Technology Agency",
      sector: "public",
      source: "eTenders",
      lane: "ICT / IS",
      stage: "Reviewing",
      closingAt: at(12, 16),
      briefingAt: at(4, 9),
      briefingCompulsory: true,
      briefingVenue: "SITA Erasmuskloof",
      estimatedValueZar: null,
      sourceUrl: "https://www.etenders.gov.za",
      ownerName: "Intake",
      opportunityType: "panel",
      isPanel: true,
      panelMaxParticipants: 20,
      panelTerm: "36-month framework agreement",
      relevanceScore: 84,
      lowRelevance: false,
      province: "Gauteng",
      category: "Information and communication",
      ocdsMainCategory: "services",
      matchVia: "category",
      contentHash: "seed-ict-panel-v2",
      inPipeline: true,
      documentLinks: [
        {
          title: "Panel terms of reference",
          url: "https://www.etenders.gov.za",
          format: "application/pdf",
        },
      ],
      contactName: "Panel Secretariat",
      contactEmail: "panels@sita.co.za",
      contactPhone: null,
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
    base({
      id: "seed-saqa-asset",
      refNo: "RFQ-SAQA-2026-041",
      title: "Asset verification system refresh",
      description:
        "Supply and implement an asset verification solution for SAQA facilities, including tagging, mobile capture and reporting.",
      buyer: "SAQA",
      sector: "public",
      source: "eTenders",
      lane: "Asset management",
      stage: "Reviewing",
      closingAt: at(2, 11),
      briefingAt: at(1, 10),
      briefingCompulsory: true,
      briefingVenue: "Virtual — MS Teams",
      estimatedValueZar: 850000,
      sourceUrl: "https://www.etenders.gov.za",
      ownerName: "Ndumiso Somdyala",
      opportunityType: "rfq",
      relevanceScore: 48,
      province: "Gauteng",
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
    base({
      id: "seed-gep-web",
      refNo: "RFQ-GEP-2026-118",
      title: "Website migration and maintenance",
      description:
        "Migrate the existing GEP website to a modern CMS, including content migration, accessibility fixes and 12-month maintenance.",
      buyer: "GEP",
      sector: "public",
      source: "eTenders",
      lane: "Website",
      stage: "Submitted",
      closingAt: at(7, 16),
      estimatedValueZar: 420000,
      sourceUrl: "https://www.etenders.gov.za",
      ownerName: "Bid Team Member",
      opportunityType: "rfq",
      relevanceScore: 36,
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
    base({
      id: "seed-sita-ict",
      refNo: "RFQ-SITA-2607-09",
      title: "ICT software licence and support",
      description:
        "Provision of ICT software licences and associated support services for a SITA client department.",
      buyer: "SITA",
      sector: "public",
      source: "SITA",
      lane: "ICT / IS",
      stage: "Spotted",
      closingAt: at(11, 11),
      briefingAt: at(5, 9),
      briefingCompulsory: false,
      briefingVenue: "SITA Erasmuskloof",
      estimatedValueZar: 1200000,
      sourceUrl: "https://rfq.sita.co.za/RFQ/RFQInvitations.asp",
      ownerName: "Bid Team Member",
      opportunityType: "rfq",
      relevanceScore: 60,
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
    base({
      id: "seed-eskom-solar",
      refNo: "MWP2484CX",
      title: "Solar PV and electrical works — depot facilities",
      description:
        "Design, supply and install rooftop solar PV with associated electrical reticulation at selected Eskom depot sites.",
      buyer: "Eskom",
      sector: "public",
      source: "Eskom",
      lane: "Solar / electrical",
      stage: "Spotted",
      closingAt: at(14, 10),
      briefingAt: at(6, 10),
      briefingCompulsory: true,
      briefingVenue: "Megawatt Park, Sandton",
      estimatedValueZar: 3500000,
      sourceUrl: "https://www.eskom.co.za/tenders/",
      ownerName: "Thandi Molefe",
      opportunityType: "tender",
      relevanceScore: 48,
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
    base({
      id: "seed-sap-private",
      refNo: "SAP-DISC-88421",
      title: "Digitisation and website rebuild RFP",
      description:
        "Private-sector RFP posted on SAP Business Network Discovery for a South African retailer seeking a digital agency / systems partner.",
      buyer: "National retailer (via SAP Discovery)",
      sector: "private",
      source: "SAP Discovery",
      lane: "Website",
      stage: "Submitted",
      closingAt: at(9, 17),
      estimatedValueZar: 950000,
      sourceUrl: "https://www.sap.com/products/business-network/discovery",
      ownerName: "Ndumiso Somdyala",
      opportunityType: "tender",
      relevanceScore: 24,
      files: [],
      createdAt: iso,
      updatedAt: iso,
    }),
  ];
}
